import { Platform } from 'react-native';

/**
 * This is a phone app, so stretching its layout across a desktop browser reads
 * as a broken website rather than a product. On a wide screen the app is framed
 * as a phone with a short explainer beside it; below 900px (real phones and
 * tablets) none of this applies and the app fills the screen as before.
 *
 * Injected at runtime because the project builds in Expo's single-page web mode,
 * where app/+html.jsx is not used and index.html is generated by the exporter.
 */
const CSS = `
  .gg-shell { display: none; }

  @media (min-width: 900px) {
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 64px;
      padding: 32px;
      box-sizing: border-box;
      background:
        radial-gradient(1100px 560px at 15% 8%, #2b3a9e 0%, transparent 60%),
        linear-gradient(155deg, #161c4a 0%, #0f1332 100%);
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    }

    .gg-shell { display: block; max-width: 370px; color: #fff; }
    .gg-shell h1 { margin: 0 0 14px; font-size: 40px; line-height: 1.1; letter-spacing: -0.5px; }
    .gg-shell p { margin: 0 0 24px; font-size: 16px; line-height: 1.6; color: rgba(255,255,255,.72); }
    .gg-shell ol { margin: 0; padding-left: 20px; font-size: 15px; line-height: 1.9; color: rgba(255,255,255,.9); }
    .gg-shell .gg-hint { margin-top: 24px; font-size: 13px; color: rgba(255,255,255,.5); }

    /* flex:none stops the react-native-web reset from stretching the frame */
    #root {
      flex: none;
      width: 390px;
      height: 844px;
      max-height: calc(100vh - 64px);
      background: #fff;
      border: 12px solid #0b0d1a;
      border-radius: 46px;
      overflow: hidden;
      box-shadow: 0 40px 80px rgba(0,0,0,.55), 0 0 0 1px rgba(255,255,255,.06);
    }
  }
`;

const PANEL = `
  <h1>GroceryGuru</h1>
  <p>Croatian shops publish their prices every day. This compares all of them and
     works out which single shop is cheapest for your whole basket.</p>
  <ol>
    <li>Press <strong>Try the demo</strong></li>
    <li>Open <strong>Recruiter demo basket</strong></li>
    <li>Press <strong>Find Cheapest Store</strong></li>
  </ol>
  <div class="gg-hint">Open this page on your phone to use it full screen.</div>
`;

export function installDesktopFrame() {
  if (Platform.OS !== 'web' || typeof document === 'undefined') return;
  if (document.getElementById('gg-desktop-frame')) return;

  const style = document.createElement('style');
  style.id = 'gg-desktop-frame';
  style.textContent = CSS;
  document.head.appendChild(style);

  const aside = document.createElement('aside');
  aside.className = 'gg-shell';
  aside.innerHTML = PANEL;
  // Before #root so the copy sits to the left of the phone.
  document.body.insertBefore(aside, document.body.firstChild);
}
